### ISSUE TITLE
when to release 17 distortions for Tid2013?

### ISSUE THREAD

**Issue by wangjy2020** [xialeiliu/RankIQA#11]

**Comment by ranjiewwen** [comment]
- i am also look for "The code to generate 17 distortions for tid2013 dataset will be publicly available in the future." 
- you can release ?

**Comment by zjupx** [comment]
waiting

**Comment by yu1206** [comment]
waiting

**Comment by xialeiliu** [comment]
Upon the request by many researchers, we finally realease our code for generating ranking set of tid2013 (17 distortions). Hope it could be helpful to the community. But we do not guarantee that our code could generate exactly the same distortions as the original tid2013 paper due to the lack of details.

**Comment by xialeiliu** [comment]
We put the source code in local folder ./data/rank_tid2013/
